---
# tasks file for tinana-deploy/roles/base

- name: Configure motd
  ansible.builtin.template:
    src: motd.j2
    dest: /etc/motd
    owner: root
    group: root
    mode: '0644'

- name: Configure PS1 Prompt
  ansible.builtin.template:
    src: ps1prompt.sh.j2
    dest: /etc/profile.d/ps1prompt.sh
    owner: root
    group: root
    mode: '0644'

- name: Configure timezone
  community.general.timezone:
    name: America/Mexico_City

- name: Configure logrotate
  ansible.builtin.template:
    src: logrotate.conf.j2
    dest: /etc/logrotate.conf
    owner: root
    group: root
    mode: '0644'

- name: Configure dnf config for fast downloads
  ansible.builtin.template:
    src: dnf.conf.j2
    dest: /etc/dnf/dnf.conf
    owner: root
    group: root
    mode: '0644'
  when: ansible_os_family == "RedHat"

- name: Install packages
  ansible.builtin.package:
    name:
      - podman
      - python3-cryptography
      - bash-completion
      - vim
      - firewalld

- name: Enable and start firewalld
  ansible.builtin.systemd_service:
    name: firewalld
    state: started
    enabled: true
